<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <InvariantGlobalization>true</InvariantGlobalization>
    <UserSecretsId>ddb6e1e9-bfff-40fa-8841-611cc5356a0e</UserSecretsId>
    <DockerDefaultTargetOS>Windows</DockerDefaultTargetOS>
    <DockerfileContext>.</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Bogus" Version="35.5.1" />
    <PackageReference Include="iTextSharp" Version="5.5.13.3" />
    <PackageReference Include="itextsharp.xmlworker" Version="5.5.13.3" />
    <PackageReference Include="Microsoft.AspNetCore.Components.QuickGrid.EntityFrameworkAdapter" Version="8.0.4" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.19.5" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.2" />
    <PackageReference Include="PuppeteerSharp" Version="16.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Views\InitialConferencePrintViews\CodeOfEthics\" />
    <Folder Include="Views\InitialConferencePrintViews\CreditCardAR\AC_2\" />
    <Folder Include="Views\InitialConferencePrintViews\CreditCardAR\AC_3\" />
    <Folder Include="Views\InitialConferencePrintViews\GeneralEnrollmentAgreement\" />
    <Folder Include="Views\InitialConferencePrintViews\AccreditationInformation\" />
    <Folder Include="Views\InitialConferencePrintViews\StudentHolidayShedule\" />
    <Folder Include="Views\InitialConferencePrintViews\WelcomeLetter\" />
    <Folder Include="Views\InitialConferencePrintViews\SavingsCertificate\" />
    <Folder Include="Views\InitialConferencePrintViews\SharingOurSuccess\" />
    <Folder Include="Views\InitialConferencePrintViews\CoverSheet\CoverSheetAC_2\" />
    <Folder Include="Views\InitialConferencePrintViews\CoverSheet\CoverSheetAC_3\" />
    <Folder Include="Views\InitialConferencePrintViews\CoverSheet\CoverSheetAC_4\" />
    <Folder Include="Views\InitialConferencePrintViews\CoverSheet\CoverSheetAC_5\" />
    <Folder Include="Views\InitialConferencePrintViews\CoverSheet\CoverSheetAC_6\" />
    <Folder Include="Views\InitialConferencePrintViews\HuntingtonResults\" />
    <Folder Include="Views\InitialConferencePrintViews\GratefulParents\" />
    <Folder Include="Views\InitialConferencePrintViews\StayingCommitedToSuccess\" />
    <Folder Include="Views\InitialConferencePrintViews\Schedule&amp;Tution\AC_2&amp;3\" />
    <Folder Include="Views\InitialConferencePrintViews\Schedule&amp;Tution\AC_4\" />
    <Folder Include="Views\InitialConferencePrintViews\Schedule&amp;Tution\AC_5\" />
    <Folder Include="Views\InitialConferencePrintViews\TutionOptions\" />
    <Folder Include="Views\InitialConferencePrintViews\Schedule\Summer_AC_2&amp;3\" />
    <Folder Include="Views\InitialConferencePrintViews\Schedule\Summer_AC_4\" />
    <Folder Include="Views\InitialConferencePrintViews\Schedule\Summer_AC_5\" />
    <Folder Include="Views\InitialConferencePrintViews\Schedule\SchoolYear_AC_2&amp;3\" />
    <Folder Include="Views\InitialConferencePrintViews\Schedule\SchoolYear_AC_4\" />
    <Folder Include="Views\InitialConferencePrintViews\Schedule\SchoolYear_AC_5\" />
    <Folder Include="Views\InitialConferencePrintViews\StudentTests\BOEHM\" />
    <Folder Include="Views\InitialConferencePrintViews\StudentTests\HSSS\" />
    <Folder Include="Views\InitialConferencePrintViews\StudentTests\HPA\" />
    <Folder Include="Views\InitialConferencePrintViews\StudentTests\Rosner\" />
    <Folder Include="Views\InitialConferencePrintViews\StudentTests\WritingSample\" />
    <Folder Include="Views\InitialConferencePrintViews\StudentTests\ReadingReadinessLR\" />
    <Folder Include="Views\InitialConferencePrintViews\StudentTests\ReadingReadinessGK\" />
    <Folder Include="Views\InitialConferencePrintViews\StudentTests\ReadingReadiness\" />
    <Folder Include="Views\InitialConferencePrintViews\StudentTests\WOLD\" />
    <Folder Include="Views\InitialConferencePrintViews\WhatWeSeeForStudent\AC_2&amp;3\" />
    <Folder Include="Views\InitialConferencePrintViews\WhatWeSeeForStudent\AC_4\" />
    <Folder Include="Views\InitialConferencePrintViews\WhatWeSeeForStudent\AC_5\" />
    <Folder Include="Views\InitialConferencePrintViews\WhatWeSeeSoFar\AC_2&amp;3\" />
    <Folder Include="Views\InitialConferencePrintViews\WhatWeSeeSoFar\AC_4\" />
    <Folder Include="Views\InitialConferencePrintViews\WhatWeSeeSoFar\AC_5\" />
  </ItemGroup>

</Project>
